# constants used by the bot

core:
  debug: False                         # mostly prevents message auto deletion
  bot_name: Mushmom                    # change bot class name and errors
  version: 1.0.0
  hook_name: Mushmom
  default_prefix: "mush "
  embed_color: 0xf49c00                # current color matching pfp
  embed_bg_color: 0x2f3136
  max_chars: 5                         # reactions will break if > 9
  default_delay: 10                    # for auto deletion
  delayed_react_time: 2                # default secs to add a delayed reaction
  default_pfp_size: 80                 # pixels
  max_fame_limit: 10

discord:
  uploads: 901105805628162099          # channel that can be sent to

database:                              # mongodb
  name: mushmom

mapleio:
  api_url: https://maplestory.io/api
  default_version: "225"               # should be a string
  body_height: 33                      # unscaled
                                       # see scripts/get_sprite_sizes.py
